# Generated by Django 6.0.3 on 2026-04-05 01:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fine_status', models.CharField(choices=[('NA', 'Not Applicable'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='NA', max_length=10)),
                ('fine_paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookissue_set', to='books.book')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transactions', to=settings.AUTH_USER_MODEL)),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookissue_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Issue',
                'verbose_name_plural': 'Book Issues',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'return_date'], name='transaction_user_id_fcd6bc_idx'), models.Index(fields=['book', 'return_date'], name='transaction_book_id_85c1b7_idx'), models.Index(fields=['due_date'], name='transaction_due_dat_b3c7ba_idx')],
            },
        ),
    ]
